### ISSUE TITLE
TARS active cutting minutes not tracking

### ISSUE THREAD

**Issue by MakerLabs-Van** [MakerLabsVan/makerlabs-acm#12] opened 2018-12-05 23:02 UTC
The google spreadsheet does not appear to be tracking the usage properly. Example provided the user actually used closer to 45 minutes they estimated.
![screen shot 2018-12-05 at 3 01 26 pm](https://user-images.githubusercontent.com/45299573/49549812-bb8e8180-f89e-11e8-9c45-b38f425d09b5.png)

**Comment by paulreimer** [comment] 2018-12-06 21:55
Noted this is still occurring, so added some additional logs to locate at what step the issue is encountered.

**Comment by paulreimer** [comment] 2018-12-07 21:04
Observed the logs, and found the step that is failing consistently is searching the spreadsheet for the matching user (from the Tag ID).

I made a small change to how the request is made (fresh connection+client each time, not re-using a previous connection), so I will continue monitoring the logs on that step.

**Comment by paulreimer** [comment] 2018-12-09 01:32
I believe this issue (and #8) are resolved now via the change described above. In the last 24hrs there have been no such errors, whereas before it would be usual to expect several in that time range.

I will wait an additional 24hrs before closing this issue and #8 as resolved.

**Comment by paulreimer** [comment] 2018-12-10 01:12
Seems good after a few days, 0 occurrences of the issue.

**Closed** 2018-12-10 01:12 UTC
